//#define _CRTDBG_MAP_ALLOC
//#include <stdlib.h>
//#include <crtdbg.h>

#include "mg_args.cpp"
#include "mg_assert.cpp"
#include "mg_dataset.cpp"
//#include "mg_file_format.cpp"
#include "mg_filesystem.cpp"
#include "mg_io.cpp"
#include "mg_logger.cpp"
#include "mg_math.cpp"
#include "mg_memory.cpp"
#include "mg_memory_map.cpp"
#include "mg_signal_processing.cpp"
#include "mg_stacktrace.cpp"
#include "mg_string.cpp"
#include "mg_utils.cpp"
#include "mg_wavelet.cpp"
#include "mg_wz.cpp"
#include "wz_v0.cpp"
#include "mg_varint.cpp"
#include "mg_volume.cpp"
#include "mg_zfp.cpp"
